spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring-cloud-sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.56.102
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.56.102
    port: 6379
env:
  dev

boy:
  name: ted
  age: 25
