spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring-cloud-sell?characterEncoding=utf-8&useSSL=false
env:
  dev

boy:
  name: ted
  age: 7
